feat - Update footer, community links, and implement dark mode on landing page
NoshonNetworks/landver pull request #101
Opened 2024-10-24 22:45 UTC by Eche5

…Page

## Detailed Information

---

## Related Issues

Closes #<issue-number>

---

## Type of Change

- [X] 🐛 Bug fix or ⚙️ enhancement
- [X] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [X] The code follows the style guidelines of this project.
- [X] All new and existing tests pass.
- [X] This pull request is ready to be merged and reviewed.

2024-10-25 04:05 UTC, fishonamos commented
Please always fix on original pr for tracking purpose.

2024-10-25 08:03 UTC, Eche5 commented
@Solomonsolomonsolomon, could you please review this PR?

2024-10-25 10:56 UTC, Solomonsolomonsolomon commented
@Eche5 can you please link the issue number to the PR,

> template for linking was provided in the Related issues section  in the PR

2024-10-25 12:32 UTC, Eche5 commented
> @Eche5 can you please link the issue number to the PR,
> 
> > template for linking was provided in the Related issues section  in the PR



> @Eche5 can you please link the issue number to the PR,
> 
> > template for linking was provided in the Related issues section  in the PR

 could you please re-review

2024-10-25 12:42 UTC, Solomonsolomonsolomon requested changes
dark mode not implemented in about page

2024-10-25 12:42 UTC, Solomonsolomonsolomon commented on landing_page/src/app/components/Footer.tsx
> +        </div>
please centralize this, it is currently aligned to the left

2024-10-25 21:07 UTC, Solomonsolomonsolomon requested changes

2024-10-25 21:07 UTC, Solomonsolomonsolomon commented on landing_page/package.json
running npm run dev gives build issues, fix the issues as app doesnt compile

2024-10-26 12:08 UTC, Solomonsolomonsolomon approved these changes
LGTM!

2024-10-26 17:58 UTC, merged