Implemented error catcher & 404 page with Sentry logging
NoshonNetworks/landver pull request #209
Opened 2024-12-01 18:59 UTC by jedstroke

## Detailed Information

![image](https://github.com/user-attachments/assets/85313dd9-edd4-4bf1-b9a6-79cecb1eb2a1)
*<small>404 page</small>*

![image](https://github.com/user-attachments/assets/9c5e509b-853c-4e76-8455-f629dd54d0c8)
*<small>Error logging UI</small>*

![image](https://github.com/user-attachments/assets/d3feaa95-d3e0-45a6-9fff-9bac2be61452)
*<small>Error logger dashboard Sentry</small>*

## Related Issues

Closes #181

---

## Type of Change

- [x] 🐛 Bug fix or ⚙️ enhancement
- [x] ✨ New feature or Chore (change with no new features or fixes)
- [x] 📚 Documentation update

---

## Checklist 
- [x] The code follows the style guidelines of this project.
- [x] All new and existing tests pass.
- [x] This pull request is ready to be merged and reviewed.

2024-12-01 21:13 UTC, fishonamos commented
Looks cool!

2024-12-01 22:18 UTC, Solomonsolomonsolomon commented on app/client/src/app/error.tsx
> +import * as Sentry from "@sentry/nextjs"
no need to use sentry, just implement error handling using next 
read https://nextjs.org/docs/app/building-your-application/routing/error-handling for more details

2024-12-01 22:40 UTC, jedstroke commented on app/client/src/app/error.tsx
> +import * as Sentry from "@sentry/nextjs"
I will just do this

2024-12-01 23:54 UTC, fishonamos commented
Good!. You moved the doc files out of the docs folder. Can you revert them?

2024-12-01 23:55 UTC, jedstroke commented
> Good!. You moved the doc files out of the docs folder. Can you revert them?

Hang on, I am doing it now

2024-12-02 13:37 UTC, fishonamos commented
LGTM. @Solomonsolomonsolomon

2024-12-02 14:27 UTC, Solomonsolomonsolomon requested changes

2024-12-02 14:27 UTC, Solomonsolomonsolomon commented on app/client/src/lib/error-logger.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
sentry is still used here, take out sentry completely

2024-12-02 17:02 UTC, jedstroke commented on app/client/src/lib/error-logger.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
> sentry is still used here, take out sentry completely
Is that all buddy?

2024-12-03 00:08 UTC, merged

2024-12-03 17:37 UTC, Kingsuite commented
This is my observation: 
https://www.loom.com/share/d4cba707ddf34537bfd7a74f76a8fb1c