landing page redirect
NoshonNetworks/landver pull request #249
Opened 2024-12-19 00:15 UTC by Xaxxoo

## Detailed Information

---

## Related Issues

Closes #<issue-number>

---

## Type of Change

- [ ] 🐛 Bug fix or ⚙️ enhancement
- [ ] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [ ] The code follows the style guidelines of this project.
- [ ] All new and existing tests pass.
- [ ] This pull request is ready to be merged and reviewed.

2024-12-19 05:35 UTC, Solomonsolomonsolomon reviewed
@Xaxxoo you included node_modules, please remove

2024-12-19 06:48 UTC, Xaxxoo commented
> @Xaxxoo you included node_modules, please remove

removed. My bad.

2024-12-19 07:02 UTC, fishonamos commented
Please add the issue number to the description.

2024-12-22 22:56 UTC, Solomonsolomonsolomon requested changes

2024-12-22 22:56 UTC, Solomonsolomonsolomon commented on package.json
> +    "dotenv": "^16.4.7",
you're installing packages in the wrong directory

2024-12-28 18:49 UTC, Solomonsolomonsolomon requested changes

2024-12-28 18:49 UTC, Solomonsolomonsolomon commented on pnpm-lock.yaml
this is at the root folder,it is /app/client that uses a pnpm lock

2024-12-28 18:49 UTC, Solomonsolomonsolomon commented on package.json
youre installing deps in the root folder, this should be in the /land-registry-backend

2024-12-28 18:49 UTC, Solomonsolomonsolomon commented on land-registry-backend/package-lock.json
please restore file as land-registry-backend uses npm. its /app/client that uses pnpm

2024-12-28 18:49 UTC, Solomonsolomonsolomon commented on app/client/package-lock.json
app/client still has a package-lock. it should use a pnpm-lock

2024-12-31 09:47 UTC, merged