feat: add map picker for land registration
NoshonNetworks/landver pull request #251
Opened 2024-12-19 08:27 UTC by MarcusDavidG

- Add `MapPicker` component for visual coordinate selection  
- Integrate map picker into `RegisterLandModal`  
- Replace manual coordinate input with interactive map  
- Add visual marker for selected location  
- Display selected coordinates below map  

## Detailed Information

### Title  
**Add map picker for land registration coordinates**  

### Description  

#### Changes Made  
- Added new `MapPicker` component for visual coordinate selection  
- Integrated interactive map into `RegisterLandModal`  
- Replaced manual coordinate input fields with map interface  
- Added visual marker to show selected location  
- Added coordinate display below map  

#### Features  
- Users can now click on a map to select land coordinates  
- Real-time display of selected latitude and longitude  
- Visual marker shows the exact selected location  
- Map is fully interactive with zoom and pan controls  
- Maintains all existing form validation and submission logic  

#### Technical Details  
- Uses `react-leaflet` for map implementation  
- Dynamically loaded to avoid SSR issues  
- Properly handles marker icon assets  
- Maintains TypeScript type safety  
- Preserves existing form functionality  

### Testing  

To test the changes:  
1. Navigate to the land registration form.  
2. Click on the map to select a location.  
3. Verify the coordinates update.  
4. Complete other form fields.  
5. Submit the form with the selected location.  

---

## Related Issues  
Closes #240  

---

## Type of Change  

- [ ] 🐛 Bug fix or ⚙️ Enhancement  
- [ ] ✨ New feature or chore (change with no new features or fixes)  
- [ ] 📚 Documentation update  

---

## Checklist (select as many as applicable)  

- [ ] The code follows the style guidelines of this project.  
- [ ] All new and existing tests pass.  
- [ ] This pull request is ready to be merged and reviewed.

2024-12-19 22:34 UTC, Solomonsolomonsolomon requested changes
You installed a package,yet the package.json was not modified, please fix

2024-12-21 05:05 UTC, MarcusDavidG reviewed
Successfully updated the package.json by committing the package.json and package-lock.json files that include the Leaflet dependencies:
leaflet: ^1.9.4
react-leaflet: ^5.0.0
@types/leaflet: ^1.9.15

2024-12-25 16:45 UTC, fishonamos commented
@Solomonsolomonsolomon

2024-12-26 07:57 UTC, Solomonsolomonsolomon reviewed
App fails, it crashes when you open the register land modal. please fix ASAP

2024-12-26 07:57 UTC, Solomonsolomonsolomon commented on app/client/package-lock.json
we dont use package-lock as we use pnpm not npm in app/client.. revert

2024-12-26 16:10 UTC, MarcusDavidG commented
Done! All issues fix and app smoothly running.

2024-12-27 08:29 UTC, closed without merging