Inspector UI modification
NoshonNetworks/landver pull request #255
Opened 2024-12-20 08:13 UTC by Benjtalkshow

## Detailed Information

---

## Related Issues

Closes #248 

---

## Type of Change

- [x] 🐛 Bug fix or ⚙️ enhancement
- [ ] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [ ] The code follows the style guidelines of this project.
- [ ] All new and existing tests pass.
- [ ] This pull request is ready to be merged and reviewed.

2024-12-22 12:14 UTC, Solomonsolomonsolomon requested changes
looks good, however its dummy data.. replace with live data .hint: use reusable components for ease

2024-12-22 12:55 UTC, Benjtalkshow commented
> looks good, however its dummy data.. replace with live data .hint: use reusable components for ease

Alright

2024-12-25 07:58 UTC, Benjtalkshow commented
@Solomonsolomonsolomon 
### I left a message in your TG account.

2024-12-26 08:00 UTC, Solomonsolomonsolomon commented
kindly reconfirm the recipient as i didnt receive any message

2024-12-26 08:04 UTC, Benjtalkshow commented
> kindly reconfirm the recipient as i didnt receive any message

Hello @Solomonsolomonsolomon 
Please check your DM. On telegram.

2024-12-27 02:10 UTC, Benjtalkshow commented
@Solomonsolomonsolomon 
I have updated my PR.

2024-12-28 12:49 UTC, Solomonsolomonsolomon reviewed
not all pages work,some break and crash app

2024-12-28 13:04 UTC, Benjtalkshow commented
> not all pages work,some break and crash app

@Solomonsolomonsolomon 
Can you list the pages that crashes the app? Because I modified only two page where TableHeader and TableRow custom components were referenced.

2024-12-28 18:23 UTC, Solomonsolomonsolomon commented
You modified more than two files, check the files changed tab to see the files you modified
this page
app/client/src/views/inspector/Lands.tsx
throws the error
<img width="1440" alt="Screenshot 2024-12-28 at 19 22 43" src="https://github.com/user-attachments/assets/dc8214eb-c4bd-4f21-a452-f92d1912a469" />

2025-01-03 15:33 UTC, Benjtalkshow commented
Hello @Solomonsolomonsolomon 
What's the update about this PR?

2025-01-27 16:09 UTC, closed without merging