feat: startknet indexer
NoshonNetworks/landver pull request #260
Opened 2024-12-23 21:05 UTC by rajiabdul

## Detailed Information

---

## Related Issues

Closes #<issue-number>

---

## Type of Change

- [ ] 🐛 Bug fix or ⚙️ enhancement
- [ ] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [ ] The code follows the style guidelines of this project.
- [ ] All new and existing tests pass.
- [ ] This pull request is ready to be merged and reviewed.

2024-12-23 21:13 UTC, fishonamos commented
Nice. Please separate db operations.

2024-12-23 21:23 UTC, fishonamos requested changes
Overall great! Please effect the requested changes as soon as possible.

2024-12-23 21:23 UTC, fishonamos commented on land-registry-indexer/src/indexer.ts
Nice. Please separate db operations.

2024-12-23 21:23 UTC, fishonamos commented on land-registry-indexer/src/config.ts
> +      transactionStatus: "succeeded",
Use all status.

2024-12-23 21:23 UTC, fishonamos commented on land-registry-indexer/src/config.ts
> +  LAND_REGISTERED: hexToDec("0x0000000000000000000000000000000000000000000000000000000000000001"),
Use the correct event keys. 

https://sepolia.starkscan.co/contract/0x05a4054a1b1389dcd48b650637977280d32f1ad8b3027bc6c7eb606bf7e28bf5#events

2024-12-23 21:23 UTC, fishonamos commented on land-registry-indexer/src/config.ts
> +      transactionStatus: "succeeded",
Use all transaction status here.

2024-12-25 15:45 UTC, rajiabdul commented
Will push my changes now!

2024-12-25 16:23 UTC, merged